### ISSUE TITLE
Can't generate whitelists from flat-file? 

### ISSUE THREAD

**Issue by suedadam** [nbs-system/nxtool#7]
I can't seem to get it working with a flat file even with the example one.
```

[root@li1305-120 nxtool-master]# python nxtool.py -v --flat-file --whitelist
INFO:root:Running Google analytics
INFO:root:Running Image 1002
INFO:root:Running cookies
INFO:root:Running url_wide_id
INFO:root:Searching for aguments in the zone ARGS
Traceback (most recent call last):
  File "nxtool.py", line 99, in <module>
    sys.exit(main())
  File "nxtool.py", line 92, in main
    whitelist.extend(module.generate_whitelist(source, whitelist))
  File "/home/nxtool-master/nxtool/whitelists_generators/__init__.py", line 4, in wrapper
    return func(provider, wl)
  File "/home/nxtool-master/nxtool/whitelists_generators/zone_var_wide.py", line 19, in generate_whitelist
    search = provider.export_search()
AttributeError: 'FlatFile' object has no attribute 'export_search'
[root@li1305-120 nxtool-master]# 
```

**Comment by jvoisin** [comment]
Should be fixed :3
